apiVersion: apps/v1
kind: Deployment
metadata:
  name: indiaproj-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indiaproj
  template:
    metadata:
      labels:
        app: indiaproj
    spec:
      containers:
      - name: indiaproj
        image: karthikthiramdas/myjavaproj:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
