apiVersion: v1
kind: Service
metadata:
  name: indiaproj-service
spec:
  type: NodePort
  selector:
    app: indiaproj
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
